repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/hhatto/autopep8
  rev: v2.3.2
  hooks:
  - id: autopep8
- repo: https://github.com/jsh9/pydoclint
  rev: 0.8.3
  hooks:
    - id: pydoclint
      args: ['--config=pyproject.toml']
