name: Question
description: Ask us a non-urgent question, and we'll get to it as soon as we can
title: "[Question]: "
labels: ["question"]
projects: ["Harvard-Neutrino/prometheus"]
assignees:
  - MeighenBergerS
  - jlazar17
body:
  - type: input
    id: contact
    attributes:
      label: Contact details
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: How can we help?
      description: Please include as much detail as possible, such as links, references, config details, anything else that is relevant.
    validations:
      required: true
