name: Enhancement suggestion
description: Tell us how we can improve the project.
title: "[Enhancement]: "
labels: ["enhancement"]
projects: ["Harvard-Neutrino/prometheus"]
assignees:
  - MeighenBergerS
  - jlazar17
type: enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share your idea with us!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: Describe the enhancement you would like to suggest.
      description: A concise description of the enhancement.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why?
      description: Why do you think this is necessary, and how can it help the project?
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about your suggestion.

        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

    
