#!/usr/bin/env python3
"""Generate an ``om.dirs`` file for the ppc multi-PMT (nextgen) engine.

``om.dirs`` is a uniformly distributed set of directions on the unit sphere.
The engine (icecube/ppc, ``ico::ini`` + ``itype::fraq``) uses it purely as a
numerical-integration grid to compute per-sensor normalization factors at
initialization -- it is **detector-independent**. The per-detector geometry
lives in ``om.conf`` (generated by ``Detector.to_om_conf``), not here. One
shared ``om.dirs`` therefore serves every detector; more points give a more
accurate normalization integral.

Each line is ``<index> <x> <y> <z>`` with (x, y, z) a unit vector. The points
are a Fibonacci (golden-angle) spiral, which is what the existing tables use.

Usage:
    python scripts/make_om_dirs.py [N] > resources/PPC_tables/om.dirs
"""

import math
import sys


def om_dirs(n: int):
    """Yield ``n`` uniformly distributed unit directions as (i, x, y, z)."""
    golden_angle = math.pi * (3.0 - math.sqrt(5.0))
    for i in range(n):
        z = 1.0 - 2.0 * (i + 0.5) / n
        r = math.sqrt(max(0.0, 1.0 - z * z))
        theta = golden_angle * i
        yield i, r * math.cos(theta), r * math.sin(theta), z


def main() -> None:
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 1000
    for i, x, y, z in om_dirs(n):
        print(f"{i} {x:.6f} {y:.6f} {z:.6f}")


if __name__ == "__main__":
    main()
